In [ ]:
import pandas as pd
train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/data/4_train.csv', index_col=0)
test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/data/4_test.csv', index_col=0)

display(train)
display(test)

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,464357,Male,No,40,Yes,Artist,7.000000,Low,1.0,Cat_6,A
1,459624,Male,No,18,No,Healthcare,2.685211,Low,5.0,Cat_4,D
2,462672,Male,No,25,No,Healthcare,7.000000,Low,4.0,Cat_4,D
3,463360,Female,Yes,46,Yes,Artist,2.000000,Low,1.0,Cat_6,B
4,462420,Male,No,27,Yes,Healthcare,1.000000,Low,3.0,Cat_6,C
...,...,...,...,...,...,...,...,...,...,...,...
4876,465496,Male,Yes,84,Yes,Lawyer,2.685211,Low,2.0,Cat_2,C
4877,460946,Male,No,84,No,Artist,0.000000,Low,1.0,Cat_6,D
4878,466118,Female,Yes,40,No,Engineer,0.000000,Low,3.0,Cat_4,D
4879,460729,Male,Yes,36,Yes,Entertainment,9.000000,Low,4.0,Cat_6,A
4880,463270,Male,Yes,52,No,Executive,1.000000,Low,5.0,Cat_6,A

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1
0,460406,Male,Yes,36,Yes,Healthcare,3.0,Low,2.0,Cat_6
1,466890,Male,Yes,47,Yes,Artist,0.0,Average,6.0,Cat_7
2,466145,Male,Yes,56,No,Entertainment,1.0,Average,3.0,Cat_6
3,465805,Male,Yes,50,Yes,Engineer,NaN,Low,1.0,Cat_3
4,466137,Female,NaN,31,No,Healthcare,0.0,Low,4.0,Cat_6
...,...,...,...,...,...,...,...,...,...,...
1537,463734,Male,Yes,38,No,Executive,0.0,Average,3.0,Cat_6
1538,466055,Male,Yes,52,Yes,Entertainment,1.0,Average,3.0,Cat_4
1539,465689,Male,No,19,No,Healthcare,8.0,Low,4.0,Cat_3
1540,460401,Female,No,25,Yes,Artist,0.0,Low,3.0,Cat_7
1541,465215,Male,Yes,39,Yes,Executive,9.0,High,5.0,Cat_2

In [ ]:
x = train.drop(columns=['ID','Segmentation'])
y = train['Segmentation']

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4881 entries, 0 to 4880
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4881 non-null   object
 1   Ever_Married     4881 non-null   object
 2   Age              4881 non-null   int64
 3   Graduated        4881 non-null   object
 4   Profession       4881 non-null   object
 5   Work_Experience  4881 non-null   float64
 6   Spending_Score   4881 non-null   object
 7   Family_Size      4881 non-null   float64
 8   Var_1            4881 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 381.3+ KB

In [ ]:
x.isnull().sum()

Age                         0
Work_Experience             0
Family_Size                 0
Gender_Female               0
Gender_Male                 0
Ever_Married_No             0
Ever_Married_Yes            0
Graduated_No                0
Graduated_Yes               0
Profession_Artist           0
Profession_Doctor           0
Profession_Engineer         0
Profession_Entertainment    0
Profession_Executive        0
Profession_Healthcare       0
Profession_Homemaker        0
Profession_Lawyer           0
Profession_Marketing        0
Spending_Score_Average      0
Spending_Score_High         0
Spending_Score_Low          0
Var_1_Cat_1                 0
Var_1_Cat_2                 0
Var_1_Cat_3                 0
Var_1_Cat_4                 0
Var_1_Cat_5                 0
Var_1_Cat_6                 0
Var_1_Cat_7                 0
dtype: int64

In [ ]:
x.describe()

               Age  Work_Experience  Family_Size
count  4881.000000      4881.000000  4881.000000
mean     43.567916         2.685211     2.838132
std      16.687728         3.266263     1.508320
min      18.000000         0.000000     1.000000
25%      31.000000         0.000000     2.000000
50%      41.000000         1.000000     2.838132
75%      53.000000         4.000000     4.000000
max      89.000000        14.000000     9.000000

In [ ]:
for col in x.select_dtypes(include='object').columns:
  print(x[col].value_counts())
  print('\n\n')

Gender
Male      2656
Female    2225
Name: count, dtype: int64



Ever_Married
Yes    2901
No     1980
Name: count, dtype: int64



Graduated
Yes    3042
No     1839
Name: count, dtype: int64



Profession
Artist           1561
Healthcare        788
Entertainment     576
Doctor            430
Engineer          419
Lawyer            398
Executive         372
Marketing         175
Homemaker         162
Name: count, dtype: int64



Spending_Score
Low        2963
Average    1185
High        733
Name: count, dtype: int64



Var_1
Cat_6    3208
Cat_4     646
Cat_3     520
Cat_2     248
Cat_7     114
Cat_1      89
Cat_5      56
Name: count, dtype: int64

In [ ]:
x=pd.get_dummies(x,drop_first=True)
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4881 entries, 0 to 4880
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       4881 non-null   int64
 1   Work_Experience           4881 non-null   float64
 2   Family_Size               4881 non-null   float64
 3   Gender_Female             4881 non-null   bool
 4   Gender_Male               4881 non-null   bool
 5   Ever_Married_No           4881 non-null   bool
 6   Ever_Married_Yes          4881 non-null   bool
 7   Graduated_No              4881 non-null   bool
 8   Graduated_Yes             4881 non-null   bool
 9   Profession_Artist         4881 non-null   bool
 10  Profession_Doctor         4881 non-null   bool
 11  Profession_Engineer       4881 non-null   bool
 12  Profession_Entertainment  4881 non-null   bool
 13  Profession_Executive      4881 non-null   bool
 14  Profession_Healthcare     4881 non-null   bool
 15  Profession_Homemaker      4881 non-null   bool
 16  Profession_Lawyer         4881 non-null   bool
 17  Profession_Marketing      4881 non-null   bool
 18  Spending_Score_Average    4881 non-null   bool
 19  Spending_Score_High       4881 non-null   bool
 20  Spending_Score_Low        4881 non-null   bool
 21  Var_1_Cat_1               4881 non-null   bool
 22  Var_1_Cat_2               4881 non-null   bool
 23  Var_1_Cat_3               4881 non-null   bool
 24  Var_1_Cat_4               4881 non-null   bool
 25  Var_1_Cat_5               4881 non-null   bool
 26  Var_1_Cat_6               4881 non-null   bool
 27  Var_1_Cat_7               4881 non-null   bool
dtypes: bool(25), float64(2), int64(1)
memory usage: 271.7 KB

In [ ]:
from sklearn.metrics import f1_score, accuracy_score, roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0, stratify=y)

rf = RandomForestClassifier(max_depth=10)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_pred_prob = rf.predict_proba(X_test)
#print(rf_pred)
print(rf_pred_prob)
print(f1_score(y_test, rf_pred, average='macro'))
print(accuracy_score(y_test, rf_pred))
print('\n')

## xgb는 문자열 처리를 못한다 이걸 -> 수치형으로 바꿔서 판단할 수 있도록 해야하는 듯...
## 이래저래 randomforest가 짱이네..
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)
print(f1_score(y_test, xgb_pred, average='macro'))
print(accuracy_score(y_test, xgb_pred))

[[0.44173226 0.25494548 0.0799814  0.22334085]
 [0.35211629 0.2468332  0.10560562 0.29544489]
 [0.26597239 0.348487   0.24475814 0.14078247]
 ...
 [0.40015321 0.17291179 0.22089748 0.20603752]
 [0.13915029 0.24963959 0.54808275 0.06312737]
 [0.11789228 0.13052984 0.16494905 0.58662883]]
0.46881931612810324
0.48925281473899696

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2 3], got ['A' 'B' 'C' 'D']

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1542 entries, 0 to 1541
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               1542 non-null   int64
 1   Gender           1542 non-null   object
 2   Ever_Married     1520 non-null   object
 3   Age              1542 non-null   int64
 4   Graduated        1526 non-null   object
 5   Profession       1519 non-null   object
 6   Work_Experience  1400 non-null   float64
 7   Spending_Score   1542 non-null   object
 8   Family_Size      1474 non-null   float64
 9   Var_1            1530 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 132.5+ KB

In [ ]:
isn = test.isnull().sum()
isn = isn[isn!=0]
isn.index

Index(['Ever_Married', 'Graduated', 'Profession', 'Work_Experience',
       'Family_Size', 'Var_1'],
      dtype='object')

In [ ]:
for col in isn.index:
  print(test[col].value_counts())
  print('\n\n')

Ever_Married
Yes    865
No     655
Name: count, dtype: int64



Graduated
Yes    920
No     606
Name: count, dtype: int64



Profession
Artist           482
Healthcare       265
Entertainment    178
Engineer         156
Doctor           126
Executive        114
Lawyer           113
Marketing         47
Homemaker         38
Name: count, dtype: int64



Work_Experience
1.0     475
0.0     450
9.0      91
8.0      82
3.0      59
2.0      52
4.0      49
5.0      46
7.0      38
6.0      31
11.0      8
13.0      7
14.0      5
10.0      4
12.0      3
Name: count, dtype: int64



Family_Size
2.0    435
3.0    292
1.0    273
4.0    265
5.0    122
6.0     47
7.0     19
8.0     12
9.0      9
Name: count, dtype: int64



Var_1
Cat_6    1000
Cat_4     231
Cat_3     141
Cat_2      92
Cat_7      42
Cat_1      14
Cat_5      10
Name: count, dtype: int64

In [ ]:
# ['Ever_Married', 'Graduated', 'Profession', 'Work_Experience', 'Family_Size', 'Var_1']

test_pre = test.copy()
test_pre['Ever_Married'] = test_pre['Ever_Married'].fillna(test_pre['Ever_Married'].value_counts().index[0])
test_pre['Graduated'] = test_pre['Graduated'].fillna(test_pre['Graduated'].value_counts().index[0])
test_pre['Profession'] = test_pre['Profession'].fillna(test_pre['Profession'].value_counts().index[0])
test_pre['Work_Experience'] = test_pre['Work_Experience'].fillna(test_pre['Work_Experience'].mean())
# ['Ever_Married', 'Graduated', 'Profession', 'Work_Experience', 'Family_Size', 'Var_1']
test_pre['Family_Size'] = test_pre['Family_Size'].fillna(test_pre['Family_Size'].mean())
test_pre['Var_1'] = test_pre['Var_1'].fillna(test_pre['Var_1'].value_counts().index[0])
test_pre = test_pre.drop(columns=['ID'])
test_pre = pd.get_dummies(test_pre)

In [ ]:
test_pre.info()
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1542 entries, 0 to 1541
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1542 non-null   int64
 1   Work_Experience           1542 non-null   float64
 2   Family_Size               1542 non-null   float64
 3   Gender_Female             1542 non-null   bool
 4   Gender_Male               1542 non-null   bool
 5   Ever_Married_No           1542 non-null   bool
 6   Ever_Married_Yes          1542 non-null   bool
 7   Graduated_No              1542 non-null   bool
 8   Graduated_Yes             1542 non-null   bool
 9   Profession_Artist         1542 non-null   bool
 10  Profession_Doctor         1542 non-null   bool
 11  Profession_Engineer       1542 non-null   bool
 12  Profession_Entertainment  1542 non-null   bool
 13  Profession_Executive      1542 non-null   bool
 14  Profession_Healthcare     1542 non-null   bool
 15  Profession_Homemaker      1542 non-null   bool
 16  Profession_Lawyer         1542 non-null   bool
 17  Profession_Marketing      1542 non-null   bool
 18  Spending_Score_Average    1542 non-null   bool
 19  Spending_Score_High       1542 non-null   bool
 20  Spending_Score_Low        1542 non-null   bool
 21  Var_1_Cat_1               1542 non-null   bool
 22  Var_1_Cat_2               1542 non-null   bool
 23  Var_1_Cat_3               1542 non-null   bool
 24  Var_1_Cat_4               1542 non-null   bool
 25  Var_1_Cat_5               1542 non-null   bool
 26  Var_1_Cat_6               1542 non-null   bool
 27  Var_1_Cat_7               1542 non-null   bool
dtypes: bool(25), float64(2), int64(1)
memory usage: 85.8 KB
<class 'pandas.core.frame.DataFrame'>
Index: 4881 entries, 0 to 4880
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       4881 non-null   int64
 1   Work_Experience           4881 non-null   float64
 2   Family_Size               4881 non-null   float64
 3   Gender_Female             4881 non-null   bool
 4   Gender_Male               4881 non-null   bool
 5   Ever_Married_No           4881 non-null   bool
 6   Ever_Married_Yes          4881 non-null   bool
 7   Graduated_No              4881 non-null   bool
 8   Graduated_Yes             4881 non-null   bool
 9   Profession_Artist         4881 non-null   bool
 10  Profession_Doctor         4881 non-null   bool
 11  Profession_Engineer       4881 non-null   bool
 12  Profession_Entertainment  4881 non-null   bool
 13  Profession_Executive      4881 non-null   bool
 14  Profession_Healthcare     4881 non-null   bool
 15  Profession_Homemaker      4881 non-null   bool
 16  Profession_Lawyer         4881 non-null   bool
 17  Profession_Marketing      4881 non-null   bool
 18  Spending_Score_Average    4881 non-null   bool
 19  Spending_Score_High       4881 non-null   bool
 20  Spending_Score_Low        4881 non-null   bool
 21  Var_1_Cat_1               4881 non-null   bool
 22  Var_1_Cat_2               4881 non-null   bool
 23  Var_1_Cat_3               4881 non-null   bool
 24  Var_1_Cat_4               4881 non-null   bool
 25  Var_1_Cat_5               4881 non-null   bool
 26  Var_1_Cat_6               4881 non-null   bool
 27  Var_1_Cat_7               4881 non-null   bool
dtypes: bool(25), float64(2), int64(1)
memory usage: 271.7 KB

In [ ]:
test_pred = rf.predict(test_pre)
result = pd.DataFrame(test_pred, columns=['pred'])
result.to_csv('result.csv', index=False)
df = pd.read_csv('result.csv')
print(df)

     pred
0       D
1       C
2       B
3       B
4       D
...   ...
1537    B
1538    B
1539    D
1540    D
1541    A

[1542 rows x 1 columns]