In [73]:
import pandas as pd
train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/data/5_train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/data/5_test.csv')

display(train)
display(test)

,ID,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,10170,A Class,2012,11940,Automatic,46000,Diesel,30,64.2,2.1
1,9551,CL Class,2020,38624,Semi-Auto,19,Petrol,150,36.7,2.0
2,1790,A Class,2013,8500,Manual,69031,Petrol,125,51.4,1.6
3,10018,B Class,2015,13998,Automatic,34739,Diesel,125,56.5,2.1
4,142,E Class,2017,20998,Semi-Auto,21352,Diesel,20,72.4,2.0
...,...,...,...,...,...,...,...,...,...,...
9818,5612,S Class,2016,79950,Semi-Auto,25317,Petrol,570,24.1,6.0
9819,9661,C Class,2016,16000,Manual,34903,Diesel,20,68.9,2.1
9820,10521,A Class,2015,11295,Automatic,86890,Diesel,20,64.2,2.1
9821,9914,A Class,2016,11849,Manual,27958,Diesel,0,80.7,1.5
9822,1468,C Class,2015,13448,Semi-Auto,31878,Diesel,20,65.7,2.1

,ID,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
0,0,SLK,2005,Automatic,63000,Petrol,325,32.1,1.8
1,2,SL CLASS,2016,Automatic,6200,Petrol,555,28.0,5.5
2,14,GLA Class,2016,Automatic,41713,Diesel,125,56.6,2.1
3,15,B Class,2017,Automatic,24841,Diesel,150,68.9,1.5
4,18,B Class,2017,Automatic,14128,Diesel,150,68.9,2.1
...,...,...,...,...,...,...,...,...,...
3291,13096,GLE Class,2016,Automatic,27804,Diesel,260,42.8,3.0
3292,13098,C Class,2019,Automatic,10635,Petrol,145,44.1,1.5
3293,13101,GLC Class,2016,Automatic,14000,Diesel,125,56.5,2.1
3294,13109,A Class,2017,Automatic,20477,Diesel,145,68.9,2.1
3295,13112,C Class,2019,Automatic,5000,Diesel,145,61.4,2.0

In [74]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9823 entries, 0 to 9822
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            9823 non-null   int64
 1   model         9823 non-null   object
 2   year          9823 non-null   int64
 3   price         9823 non-null   int64
 4   transmission  9823 non-null   object
 5   mileage       9823 non-null   int64
 6   fuelType      9823 non-null   object
 7   tax           9823 non-null   int64
 8   mpg           9823 non-null   float64
 9   engineSize    9823 non-null   float64
dtypes: float64(2), int64(5), object(3)
memory usage: 767.6+ KB

In [75]:
for col in train.select_dtypes(include='object').columns:
  print(train[col].value_counts())
  print('\n\n')

model
 C Class      2805
 A Class      1906
 E Class      1460
 GLC Class     725
 GLA Class     642
 B Class       439
 CL Class      370
 GLE Class     347
 SL CLASS      207
 CLS Class     178
 V Class       162
 S Class       142
 GL Class       89
 SLK            68
 CLA Class      65
 X-CLASS        61
 M Class        61
 GLS Class      57
 GLB Class      15
 G Class        10
 CLK             6
 CLC Class       3
 R Class         2
230              1
180              1
200              1
Name: count, dtype: int64



transmission
Semi-Auto    5146
Automatic    3616
Manual       1059
Other           2
Name: count, dtype: int64



fuelType
Diesel    6864
Petrol    2825
Hybrid     127
Other        7
Name: count, dtype: int64

In [76]:
train.describe()

,ID,year,price,mileage,tax,mpg,engineSize
count,9823.000000,9823.000000,9823.000000,9823.000000,9823.000000,9823.000000,9823.000000
mean,6537.860328,2017.291764,24725.670671,21920.129797,129.983712,55.085100,2.073073
std,3788.746072,2.239658,11849.430688,21266.824972,64.754362,15.341871,0.572922
min,1.000000,1970.000000,650.000000,1.000000,0.000000,1.100000,0.000000
25%,3247.500000,2016.000000,17450.000000,6058.500000,125.000000,45.600000,1.800000
50%,6516.000000,2018.000000,22480.000000,15181.000000,145.000000,56.500000,2.000000
75%,9816.500000,2019.000000,28990.000000,31695.500000,145.000000,64.200000,2.100000
max,13118.000000,2020.000000,154998.000000,259000.000000,580.000000,217.300000,6.200000

In [77]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

train_pre = train.copy()
train_pre = train_pre.drop(columns=['ID'])
train_pre = train_pre[~train_pre['model'].isin(['230','180','200'])]
train_pre = train_pre[~train_pre['fuelType'].isin(['Other'])]
train_pre = train_pre[~train_pre['transmission'].isin(['Other'])]
sc = StandardScaler()
sc.fit(train_pre[['year', 'mileage', 'tax', 'mpg']])
train_pre[['year', 'mileage', 'tax', 'mpg']] = sc.transform(train_pre[['year', 'mileage', 'tax', 'mpg']])

le = LabelEncoder()
le.fit(train_pre['model'])
train_pre['model'] = le.transform(train_pre['model'])

train_pre = pd.get_dummies(train_pre, drop_first=True)
train_pre.info()

x=train_pre.drop(columns=['price'])
y=train_pre['price']

<class 'pandas.core.frame.DataFrame'>
Index: 9812 entries, 0 to 9822
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   model                   9812 non-null   int64
 1   year                    9812 non-null   float64
 2   price                   9812 non-null   int64
 3   mileage                 9812 non-null   float64
 4   tax                     9812 non-null   float64
 5   mpg                     9812 non-null   float64
 6   engineSize              9812 non-null   float64
 7   transmission_Manual     9812 non-null   bool
 8   transmission_Semi-Auto  9812 non-null   bool
 9   fuelType_Hybrid         9812 non-null   bool
 10  fuelType_Petrol         9812 non-null   bool
dtypes: bool(4), float64(5), int64(2)
memory usage: 651.6 KB

In [78]:
import numpy as np
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)

rf = RandomForestRegressor()
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_train_pred = rf.predict(X_train)

test_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
train_rmse = np.sqrt(mean_squared_error(y_train, rf_train_pred))
print(test_rmse)
print(train_rmse)

2634.9663061481683
989.8882858435983

In [79]:
test.info()
test.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3296 entries, 0 to 3295
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            3296 non-null   int64
 1   model         3296 non-null   object
 2   year          3296 non-null   int64
 3   transmission  3296 non-null   object
 4   mileage       3296 non-null   int64
 5   fuelType      3296 non-null   object
 6   tax           3296 non-null   int64
 7   mpg           3296 non-null   float64
 8   engineSize    3293 non-null   float64
dtypes: float64(2), int64(4), object(3)
memory usage: 231.9+ KB

ID              0
model           0
year            0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      3
dtype: int64

In [80]:
test['engineSize'] = test['engineSize'].fillna(test['engineSize'].mean())

In [81]:
test_pre = test.copy()
test_pre = test_pre.drop(columns=['ID'])
test_pre['model'] = test_pre['model'].str.replace('220',  ' C Class')
print(set(train['model']) -set(test_pre['model']) )
print(set(test_pre['model']) - set(train['model']))
print(set(test_pre['fuelType']) - set(train['fuelType']))
test_pre['model'] = le.transform(test_pre['model'])
test_pre = pd.get_dummies(test_pre, drop_first=True)

test_pre[['year', 'mileage', 'tax', 'mpg']] = sc.transform(test_pre[['year', 'mileage', 'tax', 'mpg']])

test_pre.info()
train_pre.info()
#le = LabelEncoder()
#le.fit(train_pre['model'])
#train_pre['model'] = le.transform(train_pre['model'])

#train_pre = pd.get_dummies(train_pre, drop_first=True)
#train_pre.info()

{' CLC Class', '230', ' R Class', '180', '200'}
set()
set()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3296 entries, 0 to 3295
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   model                   3296 non-null   int64
 1   year                    3296 non-null   float64
 2   mileage                 3296 non-null   float64
 3   tax                     3296 non-null   float64
 4   mpg                     3296 non-null   float64
 5   engineSize              3296 non-null   float64
 6   transmission_Manual     3296 non-null   bool
 7   transmission_Semi-Auto  3296 non-null   bool
 8   fuelType_Hybrid         3296 non-null   bool
 9   fuelType_Petrol         3296 non-null   bool
dtypes: bool(4), float64(5), int64(1)
memory usage: 167.5 KB
<class 'pandas.core.frame.DataFrame'>
Index: 9812 entries, 0 to 9822
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   model                   9812 non-null   int64
 1   year                    9812 non-null   float64
 2   price                   9812 non-null   int64
 3   mileage                 9812 non-null   float64
 4   tax                     9812 non-null   float64
 5   mpg                     9812 non-null   float64
 6   engineSize              9812 non-null   float64
 7   transmission_Manual     9812 non-null   bool
 8   transmission_Semi-Auto  9812 non-null   bool
 9   fuelType_Hybrid         9812 non-null   bool
 10  fuelType_Petrol         9812 non-null   bool
dtypes: bool(4), float64(5), int64(2)
memory usage: 651.6 KB

In [82]:
rf_test_pred = rf.predict(test_pre)
rf_test_pred

array([ 4847.19      , 70338.39      , 17229.23      , ...,
       24192.29      , 17104.83      , 29353.29166667])

In [85]:
df = pd.DataFrame(rf_test_pred, columns=['pred'])
df

              pred
0      4847.190000
1     70338.390000
2     17229.230000
3     14446.860000
4     16259.060000
...            ...
3291  28425.050000
3292  24670.900000
3293  24192.290000
3294  17104.830000
3295  29353.291667

[3296 rows x 1 columns]

In [86]:
df.to_csv('result.csv', index=False)
result = pd.read_csv('result.csv')
print(result)

              pred
0      4847.190000
1     70338.390000
2     17229.230000
3     14446.860000
4     16259.060000
...            ...
3291  28425.050000
3292  24670.900000
3293  24192.290000
3294  17104.830000
3295  29353.291667

[3296 rows x 1 columns]