In [1]:
import pandas as pd
#데이터 로드
x_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_train.csv")
y_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/y_train.csv")
x_test= pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_test.csv")


display(x_train.head())
display(y_train.head())

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,25298,city_138,0.836,Male,No relevent experience,Full time course,High School,NaN,5,100-500,Pvt Ltd,1,45
1,4241,city_160,0.920,Male,No relevent experience,Full time course,High School,NaN,5,NaN,NaN,1,17
2,24086,city_57,0.866,Male,No relevent experience,no_enrollment,Graduate,STEM,10,NaN,NaN,1,50
3,26773,city_16,0.910,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,>4,135
4,32325,city_143,0.740,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,17

   enrollee_id  target
0        25298     0.0
1         4241     1.0
2        24086     0.0
3        26773     0.0
4        32325     1.0

In [3]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12452 entries, 0 to 12451
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             12452 non-null  int64
 1   city                    12452 non-null  object
 2   city_development_index  12452 non-null  float64
 3   gender                  9535 non-null   object
 4   relevent_experience     12452 non-null  object
 5   enrolled_university     12195 non-null  object
 6   education_level         12137 non-null  object
 7   major_discipline        10586 non-null  object
 8   experience              12415 non-null  object
 9   company_size            8600 non-null   object
 10  company_type            8471 non-null   object
 11  last_new_job            12179 non-null  object
 12  training_hours          12452 non-null  int64
dtypes: float64(1), int64(2), object(10)
memory usage: 1.2+ MB

In [5]:
x_train.select_dtypes(include='object')

,city,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job
0,city_138,Male,No relevent experience,Full time course,High School,NaN,5,100-500,Pvt Ltd,1
1,city_160,Male,No relevent experience,Full time course,High School,NaN,5,NaN,NaN,1
2,city_57,Male,No relevent experience,no_enrollment,Graduate,STEM,10,NaN,NaN,1
3,city_16,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,>4
4,city_143,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never
...,...,...,...,...,...,...,...,...,...,...
12447,city_21,Male,Has relevent experience,no_enrollment,Graduate,STEM,<1,50-99,Pvt Ltd,1
12448,city_103,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4
12449,city_160,Female,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,1
12450,city_160,Male,Has relevent experience,Full time course,Graduate,STEM,10,NaN,NaN,2
12451,city_136,NaN,No relevent experience,Full time course,Graduate,STEM,4,NaN,NaN,1

In [10]:
for col in x_train.select_dtypes(include='object').columns:
  print(x_train[col].value_counts())
  print('\n''\n')

city
city_103    2839
city_21     1713
city_16     1005
city_114     854
city_160     557
            ...
city_18        2
city_129       1
city_121       1
city_166       1
city_140       1
Name: count, Length: 122, dtype: int64



gender
Male      8595
Female     808
Other      132
Name: count, dtype: int64



relevent_experience
Has relevent experience    8953
No relevent experience     3499
Name: count, dtype: int64



enrolled_university
no_enrollment       8975
Full time course    2431
Part time course     789
Name: count, dtype: int64



education_level
Graduate          7540
Masters           2796
High School       1336
Phd                269
Primary School     196
Name: count, dtype: int64



major_discipline
STEM               9414
Humanities          436
Other               248
Business Degree     195
Arts                157
No Major            136
Name: count, dtype: int64



experience
>20    2179
4       945
5       926
3       858
6       795
2       713
7       661
9       657
10      633
8       520
15      470
11      428
14      368
1       354
16      334
<1      331
12      317
13      260
17      224
19      200
18      151
20       91
Name: count, dtype: int64



company_size
50-99        2000
100-500      1672
10000+       1337
10/49         947
1000-4999     852
<10           838
500-999       599
5000-9999     355
Name: count, dtype: int64



company_type
Pvt Ltd                6413
Funded Startup          652
Public Sector           620
Early Stage Startup     365
NGO                     340
Other                    81
Name: count, dtype: int64



last_new_job
1        5157
>4       2182
2        1895
never    1584
3         685
4         676
Name: count, dtype: int64

In [12]:
x_train.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    2917
relevent_experience          0
enrolled_university        257
education_level            315
major_discipline          1866
experience                  37
company_size              3852
company_type              3981
last_new_job               273
training_hours               0
dtype: int64

In [20]:
x_train.shape

(12452, 13)

In [26]:
#결측치 처리
#enrolled_university, education_level, experience, last_new_job 정도는 최빈값으로 대체하면 될 듯
#gender, major_discipline, company_size, company_type 은 어떻게 해야할까?

x_train['enrolled_university'] = x_train['enrolled_university'].fillna(x_train['enrolled_university'].value_counts().index[0])
x_train['education_level'] = x_train['education_level'].fillna(x_train['education_level'].value_counts().index[0])
x_train['experience'] = x_train['experience'].fillna(x_train['experience'].value_counts().index[0])
x_train['last_new_job'] = x_train['last_new_job'].fillna(x_train['last_new_job'].value_counts().index[0])

In [30]:
x_train['gender'] = x_train['gender'].fillna('unknown')
x_train['major_discipline'] = x_train['major_discipline'].fillna('unknown')
x_train['company_type'] = x_train['company_type'].fillna('unknown')
x_train['company_size'] = x_train['company_size'].fillna('unknown')

In [32]:
x_train.isnull().sum()

enrollee_id               0
city                      0
city_development_index    0
gender                    0
relevent_experience       0
enrolled_university       0
education_level           0
major_discipline          0
experience                0
company_size              0
company_type              0
last_new_job              0
training_hours            0
dtype: int64

In [34]:
for col in x_train.select_dtypes(include='object').columns:
  print(x_train[col].value_counts())
  print('\n''\n')

city
city_103    2839
city_21     1713
city_16     1005
city_114     854
city_160     557
            ...
city_18        2
city_129       1
city_121       1
city_166       1
city_140       1
Name: count, Length: 122, dtype: int64



gender
Male       8595
unknown    2917
Female      808
Other       132
Name: count, dtype: int64



relevent_experience
Has relevent experience    8953
No relevent experience     3499
Name: count, dtype: int64



enrolled_university
no_enrollment       9232
Full time course    2431
Part time course     789
Name: count, dtype: int64



education_level
Graduate          7855
Masters           2796
High School       1336
Phd                269
Primary School     196
Name: count, dtype: int64



major_discipline
STEM               9414
unknown            1866
Humanities          436
Other               248
Business Degree     195
Arts                157
No Major            136
Name: count, dtype: int64



experience
>20    2216
4       945
5       926
3       858
6       795
2       713
7       661
9       657
10      633
8       520
15      470
11      428
14      368
1       354
16      334
<1      331
12      317
13      260
17      224
19      200
18      151
20       91
Name: count, dtype: int64



company_size
unknown      3852
50-99        2000
100-500      1672
10000+       1337
10/49         947
1000-4999     852
<10           838
500-999       599
5000-9999     355
Name: count, dtype: int64



company_type
Pvt Ltd                6413
unknown                3981
Funded Startup          652
Public Sector           620
Early Stage Startup     365
NGO                     340
Other                    81
Name: count, dtype: int64



last_new_job
1        5430
>4       2182
2        1895
never    1584
3         685
4         676
Name: count, dtype: int64

In [37]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12452 entries, 0 to 12451
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             12452 non-null  int64
 1   city                    12452 non-null  object
 2   city_development_index  12452 non-null  float64
 3   gender                  12452 non-null  object
 4   relevent_experience     12452 non-null  object
 5   enrolled_university     12452 non-null  object
 6   education_level         12452 non-null  object
 7   major_discipline        12452 non-null  object
 8   experience              12452 non-null  object
 9   company_size            12452 non-null  object
 10  company_type            12452 non-null  object
 11  last_new_job            12452 non-null  object
 12  training_hours          12452 non-null  int64
dtypes: float64(1), int64(2), object(10)
memory usage: 1.2+ MB

In [41]:
x_train.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,25298,city_138,0.836,Male,No relevent experience,Full time course,High School,unknown,5,100-500,Pvt Ltd,1,45
1,4241,city_160,0.920,Male,No relevent experience,Full time course,High School,unknown,5,unknown,unknown,1,17
2,24086,city_57,0.866,Male,No relevent experience,no_enrollment,Graduate,STEM,10,unknown,unknown,1,50
3,26773,city_16,0.910,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,>4,135
4,32325,city_143,0.740,unknown,No relevent experience,Full time course,Graduate,STEM,5,unknown,unknown,never,17

In [44]:
x_train.describe()

        enrollee_id  city_development_index  training_hours
count  12452.000000            12452.000000    12452.000000
mean   16966.301076                0.829709       65.604481
std     9646.223269                0.123087       60.430340
min        1.000000                0.448000        1.000000
25%     8591.500000                0.740000       23.000000
50%    17177.500000                0.910000       47.000000
75%    25327.750000                0.920000       88.000000
max    33380.000000                0.949000      336.000000

In [48]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

sc = StandardScaler()
sc.fit(x_train[['training_hours']])
x_train[['training_hours']] = sc.transform(x_train[['training_hours']])
x_train.describe()

        enrollee_id  city_development_index  training_hours
count  12452.000000            12452.000000    1.245200e+04
mean   16966.301076                0.829709    2.168376e-17
std     9646.223269                0.123087    1.000040e+00
min        1.000000                0.448000   -1.069117e+00
25%     8591.500000                0.740000   -7.050464e-01
50%    17177.500000                0.910000   -3.078789e-01
75%    25327.750000                0.920000    3.706155e-01
max    33380.000000                0.949000    4.474679e+00

In [49]:
x_train = x_train.drop(columns=['enrollee_id'])
y_train = y_train.drop(columns=['enrollee_id'])

In [50]:
#label을 할 것인지 get_dummies를 할 것인지..
#label
# experience
#get_dummies
#gender, relevent_exp, enrolled_university, education_level, experience빼고 다 해도 될 듯?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12452 entries, 0 to 12451
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   city                    12452 non-null  object
 1   city_development_index  12452 non-null  float64
 2   gender                  12452 non-null  object
 3   relevent_experience     12452 non-null  object
 4   enrolled_university     12452 non-null  object
 5   education_level         12452 non-null  object
 6   major_discipline        12452 non-null  object
 7   experience              12452 non-null  object
 8   company_size            12452 non-null  object
 9   company_type            12452 non-null  object
 10  last_new_job            12452 non-null  object
 11  training_hours          12452 non-null  float64
dtypes: float64(2), object(10)
memory usage: 1.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12452 entries, 0 to 12451
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   target  12452 non-null  float64
dtypes: float64(1)
memory usage: 97.4 KB

In [61]:
le = LabelEncoder()
le.fit(x_train['experience'])
x_train['experience'] = le.transform(x_train['experience'])
le2 = LabelEncoder()
le2.fit(x_train['company_size'])
x_train['company_size'] = le2.transform(x_train['company_size'])

In [64]:
x_train = pd.get_dummies(
    x_train,
    columns=['gender', 'relevent_experience', 'enrolled_university',
             'education_level', 'major_discipline', 'company_type', 'last_new_job'],
    drop_first=True
)

In [56]:
x_train = x_train.drop(columns=['city'])

In [66]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12452 entries, 0 to 12451
Data columns (total 31 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   city_development_index                      12452 non-null  float64
 1   experience                                  12452 non-null  int64
 2   company_size                                12452 non-null  int64
 3   training_hours                              12452 non-null  float64
 4   gender_Male                                 12452 non-null  bool
 5   gender_Other                                12452 non-null  bool
 6   gender_unknown                              12452 non-null  bool
 7   relevent_experience_No relevent experience  12452 non-null  bool
 8   enrolled_university_Part time course        12452 non-null  bool
 9   enrolled_university_no_enrollment           12452 non-null  bool
 10  education_level_High School                 12452 non-null  bool
 11  education_level_Masters                     12452 non-null  bool
 12  education_level_Phd                         12452 non-null  bool
 13  education_level_Primary School              12452 non-null  bool
 14  major_discipline_Business Degree            12452 non-null  bool
 15  major_discipline_Humanities                 12452 non-null  bool
 16  major_discipline_No Major                   12452 non-null  bool
 17  major_discipline_Other                      12452 non-null  bool
 18  major_discipline_STEM                       12452 non-null  bool
 19  major_discipline_unknown                    12452 non-null  bool
 20  company_type_Funded Startup                 12452 non-null  bool
 21  company_type_NGO                            12452 non-null  bool
 22  company_type_Other                          12452 non-null  bool
 23  company_type_Public Sector                  12452 non-null  bool
 24  company_type_Pvt Ltd                        12452 non-null  bool
 25  company_type_unknown                        12452 non-null  bool
 26  last_new_job_2                              12452 non-null  bool
 27  last_new_job_3                              12452 non-null  bool
 28  last_new_job_4                              12452 non-null  bool
 29  last_new_job_>4                             12452 non-null  bool
 30  last_new_job_never                          12452 non-null  bool
dtypes: bool(27), float64(2), int64(2)
memory usage: 717.6 KB

In [67]:
from sklearn.model_selection import train_test_split
x_tr, x_te, y_tr, y_te = train_test_split(x_train, y_train, test_size=0.2, random_state=0, stratify=y_train)

In [72]:
x_tr.shape
y_tr.shape

(9961, 1)

In [110]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0,max_depth=15)
rf.fit(x_tr, y_tr)
rf_pred = rf.predict(x_te)
rf_pred
rf_pred_prob = rf.predict_proba(x_te)
rf_pred_prob

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

array([[0.88844125, 0.11155875],
       [0.83640247, 0.16359753],
       [0.90990057, 0.09009943],
       ...,
       [0.46796128, 0.53203872],
       [0.69446804, 0.30553196],
       [0.90203118, 0.09796882]])

In [111]:
from sklearn.metrics import f1_score
score = f1_score(y_te, rf_pred)
score

0.5317115551694179

In [115]:
from sklearn.metrics import roc_auc_score, accuracy_score
score = accuracy_score(y_te, rf_pred)
score

0.7836210357286231

In [117]:
score = roc_auc_score(y_te, rf_pred_prob[:,1])
score

np.float64(0.7865108889405564)

In [105]:
x_test = x_test.drop(columns=['enrollee_id', 'city'])

In [107]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6706 entries, 0 to 6705
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   city_development_index  6706 non-null   float64
 1   gender                  5115 non-null   object
 2   relevent_experience     6706 non-null   object
 3   enrolled_university     6577 non-null   object
 4   education_level         6561 non-null   object
 5   major_discipline        5759 non-null   object
 6   experience              6678 non-null   object
 7   company_size            4620 non-null   object
 8   company_type            4547 non-null   object
 9   last_new_job            6556 non-null   object
 10  training_hours          6706 non-null   int64
dtypes: float64(1), int64(1), object(9)
memory usage: 576.4+ KB

In [118]:
x_test.isnull().sum()

city_development_index       0
gender                    1591
relevent_experience          0
enrolled_university        129
education_level            145
major_discipline           947
experience                  28
company_size              2086
company_type              2159
last_new_job               150
training_hours               0
dtype: int64